labtest:  lab_13_unit_test.o
	g++ -Wall -g -o labtest  lab_13_unit_test.o
	
#lab_5.o: lab_5.cpp lab_5.h  lab_5.o - lab_5.cpp DEPRECATED FILE
	#g++ -Wall -g -c lab_5.cpp lab_5.o
	
lab_13_unit_test.o: lab_13_unit_test.cpp
	g++ -Wall -g -c lab_13_unit_test.cpp
	
clean:
	rm *.o *test 