# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20171114_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='games',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
