# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20171204_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='choice_field',
            field=models.CharField(choices=[('LFG', 'Lfg'), ('LFM', 'Lfm'), ('WTB', 'Wtb'), ('WTS', 'Wts')], max_length=3),
        ),
    ]
